package de.lioncraft.velocityMain.listeners;

import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.player.ServerPostConnectEvent;
import com.velocitypowered.api.util.ServerLink;
import net.kyori.adventure.text.Component;

import java.util.List;

public class PacketListeners {
    @Subscribe
    public void onServerLinkSend(ServerPostConnectEvent e){
        e.getPlayer().setServerLinks(List.of(
                ServerLink.serverLink(Component.text("\ue000    Regelwerk"), "https://server.castcrafter.de/rules.html"),
                ServerLink.serverLink(Component.text("\ue001    Discord"), "https://discord.gg/castcrafter"),
                ServerLink.serverLink(Component.text("\ue002    Event-Informationen"), "https://server.castcrafter.de/event-server.html"),
                ServerLink.serverLink(Component.text("\ue003    Ticket erstellen (Bugreport, Unban, etc.)"), "https://discord.com/channels/133198459531558912/1297295229870800907"),
                ServerLink.serverLink(Component.text("\ue004    Updates"), "https://discord.com/channels/133198459531558912/980810495877607524"),
                ServerLink.serverLink(Component.text("\ue005    FAQ"), "https://server.castcrafter.de/faq.html")
        ));
    }
    /*

    {
        "parent":"item/generated", "textures":
    {
        "layer0":"item/paper"
    },"overrides":[{
        "predicate":{
            "custom_model_data":1000001
        },"model":"custom/factions/items/war_declaration"
    },{
        "predicate":{
            "custom_model_data":1000100
        },"model":"custom/general/specialitems/text_hologram"
    },{
        "predicate":{
            "custom_model_data":1000101
        },"model":"custom/general/items/private_teleport"
    },{
        "predicate":{
            "custom_model_data":1000102
        },"model":"custom/general/items/public_teleport"
    },{
        "predicate":{
            "custom_model_data":1000103
        },"model":"custom/general/treasurechests/treasurechest_item"
    },{
        "predicate":{
            "custom_model_data":1000105
        },"model":"custom/general/cosmetics/tools/xmas_fishing_rod_present"
    },{
        "predicate":{
            "custom_model_data":1000106
        },"model":"custom/minecraft_party/icons/reset_to_checkpoint"
    },{
        "predicate":{
            "custom_model_data":1000107
        },"model":"custom/minecraft_party/icons/players_visible"
    },{
        "predicate":{
            "custom_model_data":1000108
        },"model":"custom/minecraft_party/icons/players_invisible"
    },{
        "predicate":{
            "custom_model_data":1000109
        },"model":"custom/minecraft_party/icons/ranking"
    },{
        "predicate":{
            "custom_model_data":1000110
        },"model":"custom/general/icons/booster"
    },{
        "predicate":{
            "custom_model_data":1000111
        },"model":"custom/general/icons/info"
    },{
        "predicate":{
            "custom_model_data":1000112
        },"model":"custom/general/icons/mail_closed"
    },{
        "predicate":{
            "custom_model_data":1000113
        },"model":"custom/general/icons/mail_open"
    },{
        "predicate":{
            "custom_model_data":1000114
        },"model":"custom/general/icons/package"
    },{
        "predicate":{
            "custom_model_data":1000115
        },"model":"custom/general/icons/stopwatch"
    },{
        "predicate":{
            "custom_model_data":1000116
        },"model":"custom/general/icons/vote_closed"
    },{
        "predicate":{
            "custom_model_data":1000117
        },"model":"custom/general/icons/vote_open"
    },{
        "predicate":{
            "custom_model_data":1000118
        },"model":"custom/general/icons/backpack"
    },{
        "predicate":{
            "custom_model_data":1000119
        },"model":"custom/general/icons/balloon"
    },{
        "predicate":{
            "custom_model_data":1000120
        },"model":"custom/general/icons/hat"
    },{
        "predicate":{
            "custom_model_data":1000121
        },"model":"custom/general/icons/particle"
    },{
        "predicate":{
            "custom_model_data":1000122
        },"model":"custom/general/icons/shopping_cart"
    },{
        "predicate":{
            "custom_model_data":1000123
        },"model":"custom/general/icons/single_crystal"
    },{
        "predicate":{
            "custom_model_data":1000124
        },"model":"custom/general/icons/skill"
    },{
        "predicate":{
            "custom_model_data":1000125
        },"model":"custom/general/icons/tool"
    },{
        "predicate":{
            "custom_model_data":1000126
        },"model":"custom/minecraft_party/icons/red_candy"
    },{
        "predicate":{
            "custom_model_data":1000127
        },"model":"custom/minecraft_party/icons/controller"
    },{
        "predicate":{
            "custom_model_data":1000128
        },"model":"custom/minecraft_party/icons/parachute"
    },{
        "predicate":{
            "custom_model_data":1000129
        },"model":"custom/minecraft_party/icons/boost"
    },{
        "predicate":{
            "custom_model_data":1000130
        },"model":"custom/minecraft_party/icons/minigames/block_jumps"
    },{
        "predicate":{
            "custom_model_data":1000131
        },"model":"custom/minecraft_party/icons/minigames/collect"
    },{
        "predicate":{
            "custom_model_data":1000132
        },"model":"custom/minecraft_party/icons/minigames/colorful_chaos"
    },{
        "predicate":{
            "custom_model_data":1000133
        },"model":"custom/minecraft_party/icons/minigames/death_cube"
    },{
        "predicate":{
            "custom_model_data":1000134
        },"model":"custom/minecraft_party/icons/minigames/dropper"
    },{
        "predicate":{
            "custom_model_data":1000135
        },"model":"custom/minecraft_party/icons/minigames/duels"
    },{
        "predicate":{
            "custom_model_data":1000136
        },"model":"custom/minecraft_party/icons/minigames/elytra_race"
    },{
        "predicate":{
            "custom_model_data":1000137
        },"model":"custom/minecraft_party/icons/minigames/gun_game"
    },{
        "predicate":{
            "custom_model_data":1000138
        },"model":"custom/minecraft_party/icons/minigames/horse_race"
    },{
        "predicate":{
            "custom_model_data":1000139
        },"model":"custom/minecraft_party/icons/minigames/hot_ground"
    },{
        "predicate":{
            "custom_model_data":1000140
        },"model":"custom/minecraft_party/icons/minigames/hot_potato"
    },{
        "predicate":{
            "custom_model_data":1000141
        },"model":"custom/minecraft_party/icons/minigames/jump_and_run"
    },{
        "predicate":{
            "custom_model_data":1000142
        },"model":"custom/minecraft_party/icons/minigames/king_of_the_hill"
    },{
        "predicate":{
            "custom_model_data":1000143
        },"model":"custom/minecraft_party/icons/minigames/lasertag"
    },{
        "predicate":{
            "custom_model_data":1000144
        },"model":"custom/minecraft_party/icons/minigames/minefield"
    },{
        "predicate":{
            "custom_model_data":1000145
        },"model":"custom/minecraft_party/icons/minigames/minefight"
    },{
        "predicate":{
            "custom_model_data":1000146
        },"model":"custom/minecraft_party/icons/minigames/musical_minecarts"
    },{
        "predicate":{
            "custom_model_data":1000147
        },"model":"custom/minecraft_party/icons/minigames/one_in_the_chamber"
    },{
        "predicate":{
            "custom_model_data":1000148
        },"model":"custom/minecraft_party/icons/minigames/paintball"
    },{
        "predicate":{
            "custom_model_data":1000149
        },"model":"custom/minecraft_party/icons/minigames/race"
    },{
        "predicate":{
            "custom_model_data":1000150
        },"model":"custom/minecraft_party/icons/minigames/remember_the_sequence"
    },{
        "predicate":{
            "custom_model_data":1000151
        },"model":"custom/minecraft_party/icons/minigames/shooting_range"
    },{
        "predicate":{
            "custom_model_data":1000152
        },"model":"custom/minecraft_party/icons/minigames/skywars"
    },{
        "predicate":{
            "custom_model_data":1000153
        },"model":"custom/minecraft_party/icons/minigames/slimejump"
    },{
        "predicate":{
            "custom_model_data":1000154
        },"model":"custom/minecraft_party/icons/minigames/spleef"
    },{
        "predicate":{
            "custom_model_data":1000155
        },"model":"custom/minecraft_party/icons/minigames/survival_games"
    },{
        "predicate":{
            "custom_model_data":1000156
        },"model":"custom/minecraft_party/icons/minigames/walls"
    },{
        "predicate":{
            "custom_model_data":1000157
        },"model":"custom/minecraft_party/icons/minigames/dragon_escape"
    },{
        "predicate":{
            "custom_model_data":1000158
        },"model":"custom/minecraft_party/icons/minigames/red_light_green_light"
    },{
        "predicate":{
            "custom_model_data":1000159
        },"model":"custom/minecraft_party/icons/minigames/replica"
    },{
        "predicate":{
            "custom_model_data":1000160
        },"model":"custom/general/icons/flags/flag_de"
    },{
        "predicate":{
            "custom_model_data":1000161
        },"model":"custom/general/icons/flags/flag_de_at"
    },{
        "predicate":{
            "custom_model_data":1000162
        },"model":"custom/general/icons/flags/flag_de_ch"
    },{
        "predicate":{
            "custom_model_data":1000163
        },"model":"custom/general/icons/flags/flag_en"
    },{
        "predicate":{
            "custom_model_data":1000164
        },"model":"custom/general/icons/flags/flag_es"
    },{
        "predicate":{
            "custom_model_data":1000165
        },"model":"custom/general/icons/flags/flag_fr"
    },{
        "predicate":{
            "custom_model_data":1000166
        },"model":"custom/general/icons/flags/flag_pt"
    },{
        "predicate":{
            "custom_model_data":1000167
        },"model":"custom/general/icons/flags/flag_ru"
    },{
        "predicate":{
            "custom_model_data":1000168
        },"model":"custom/general/icons/flags/flag_mxn"
    },{
        "predicate":{
            "custom_model_data":1000169
        },"model":"custom/minecraft_party/icons/minigames/flag_quiz"
    },{
        "predicate":{
            "custom_model_data":1000170
        },"model":"custom/general/specialitems/player_shop"
    },{
        "predicate":{
            "custom_model_data":1000171
        },"model":"custom/general/icons/gamemodes/bedwars"
    },{
        "predicate":{
            "custom_model_data":1000172
        },"model":"custom/general/icons/gamemodes/cactus"
    },{
        "predicate":{
            "custom_model_data":1000173
        },"model":"custom/general/icons/gamemodes/citybuild"
    },{
        "predicate":{
            "custom_model_data":1000174
        },"model":"custom/general/icons/gamemodes/factions"
    },{
        "predicate":{
            "custom_model_data":1000175
        },"model":"custom/general/icons/gamemodes/heroes"
    },{
        "predicate":{
            "custom_model_data":1000176
        },"model":"custom/general/icons/gamemodes/minecraft_party"
    },{
        "predicate":{
            "custom_model_data":1000177
        },"model":"custom/general/icons/gamemodes/minestar"
    },{
        "predicate":{
            "custom_model_data":1000178
        },"model":"custom/general/icons/gamemodes/reallife"
    },{
        "predicate":{
            "custom_model_data":1000179
        },"model":"custom/general/icons/gamemodes/realms"
    },{
        "predicate":{
            "custom_model_data":1000180
        },"model":"custom/general/icons/gamemodes/skyblock"
    },{
        "predicate":{
            "custom_model_data":1000181
        },"model":"custom/general/icons/gamemodes/smash"
    },{
        "predicate":{
            "custom_model_data":1000182
        },"model":"custom/general/icons/gamemodes/timejump"
    },{
        "predicate":{
            "custom_model_data":1000183
        },"model":"custom/general/icons/gamemodes/ultimate_knockout"
    },{
        "predicate":{
            "custom_model_data":1000184
        },"model":"custom/general/icons/util/cancel_icon"
    },{
        "predicate":{
            "custom_model_data":1000185
        },"model":"custom/general/icons/util/check_icon"
    },{
        "predicate":{
            "custom_model_data":1000186
        },"model":"custom/general/icons/util/gray_arrow_left"
    },{
        "predicate":{
            "custom_model_data":1000187
        },"model":"custom/general/icons/util/gray_arrow_right"
    },{
        "predicate":{
            "custom_model_data":1000188
        },"model":"custom/general/icons/util/green_arrow_left"
    },{
        "predicate":{
            "custom_model_data":1000189
        },"model":"custom/general/icons/util/green_arrow_right"
    },{
        "predicate":{
            "custom_model_data":1000190
        },"model":"custom/general/icons/single_rubine"
    },{
        "predicate":{
            "custom_model_data":1000200
        },"model":"custom/general/fishing/baits/common_fishing_bait"
    },{
        "predicate":{
            "custom_model_data":1000201
        },"model":"custom/general/fishing/baits/rare_fishing_bait"
    },{
        "predicate":{
            "custom_model_data":1000202
        },"model":"custom/general/fishing/baits/epic_fishing_bait"
    },{
        "predicate":{
            "custom_model_data":1000203
        },"model":"custom/general/fishing/baits/legendary_fishing_bait"
    },{
        "predicate":{
            "custom_model_data":1000204
        },"model":"custom/general/fishing/baits/jellyfish_tentacle_bait"
    },{
        "predicate":{
            "custom_model_data":1000205
        },"model":"custom/general/fishing/baits/corn_bait"
    },{
        "predicate":{
            "custom_model_data":1000206
        },"model":"custom/general/fishing/baits/worm_bait"
    },{
        "predicate":{
            "custom_model_data":1000207
        },"model":"custom/general/fishing/baits/dough_balls_bait"
    },{
        "predicate":{
            "custom_model_data":1000300
        },"model":"custom/smash/world_repair"
    },{
        "predicate":{
            "custom_model_data":1000301
        },"model":"custom/smash/speed"
    },{
        "predicate":{
            "custom_model_data":1000302
        },"model":"custom/smash/glowing"
    },{
        "predicate":{
            "custom_model_data":1000303
        },"model":"custom/general/icons/empty"
    },{
        "predicate":{
            "custom_model_data":1000304
        },"model":"custom/minecraft_party/icons/players_half_visible"
    },{
        "predicate":{
            "custom_model_data":1000305
        },"model":"custom/general/icons/flags/flag_it"
    },{
        "predicate":{
            "custom_model_data":1000321
        },"model":"custom/factions/items/healpotion/health_potion_0"
    },{
        "predicate":{
            "custom_model_data":1000322
        },"model":"custom/factions/items/healpotion/health_potion_1"
    },{
        "predicate":{
            "custom_model_data":1000323
        },"model":"custom/factions/items/healpotion/health_potion_2"
    },{
        "predicate":{
            "custom_model_data":1000324
        },"model":"custom/factions/items/healpotion/health_potion_3"
    },{
        "predicate":{
            "custom_model_data":1000325
        },"model":"custom/factions/items/healpotion/health_potion_4"
    },{
        "predicate":{
            "custom_model_data":1000326
        },"model":"custom/factions/items/healpotion/health_potion_5"
    },{
        "predicate":{
            "custom_model_data":1000327
        },"model":"custom/factions/items/healpotion/health_potion_6"
    },{
        "predicate":{
            "custom_model_data":1000331
        },"model":"custom/factions/items/crown"
    },{
        "predicate":{
            "custom_model_data":1000332
        },"model":"custom/factions/items/fragment"
    },{
        "predicate":{
            "custom_model_data":1000333
        },"model":"custom/factions/raiditems/locks/diamond_lock"
    },{
        "predicate":{
            "custom_model_data":1000334
        },"model":"custom/factions/raiditems/locks/diamond_lock_door"
    },{
        "predicate":{
            "custom_model_data":1000335
        },"model":"custom/factions/raiditems/locks/diamond_lock_trapdoor"
    },{
        "predicate":{
            "custom_model_data":1000336
        },"model":"custom/factions/raiditems/locks/netherite_lock"
    },{
        "predicate":{
            "custom_model_data":1000337
        },"model":"custom/factions/raiditems/locks/netherite_lock_door"
    },{
        "predicate":{
            "custom_model_data":1000338
        },"model":"custom/factions/raiditems/locks/netherite_lock_trapdoor"
    },{
        "predicate":{
            "custom_model_data":1000339
        },"model":"custom/factions/raiditems/locks/silver_lock"
    },{
        "predicate":{
            "custom_model_data":1000340
        },"model":"custom/factions/raiditems/locks/silver_lock_door"
    },{
        "predicate":{
            "custom_model_data":1000341
        },"model":"custom/factions/raiditems/locks/silver_lock_trapdoor"
    },{
        "predicate":{
            "custom_model_data":1000342
        },"model":"custom/factions/items/skill_reset_scroll"
    },{
        "predicate":{
            "custom_model_data":1000343
        },"model":"custom/general/icons/crownfight_spawn"
    },{
        "predicate":{
            "custom_model_data":1000344
        },"model":"custom/general/icons/minigames/wrench"
    },{
        "predicate":{
            "custom_model_data":1000345
        },"model":"custom/citybuild/spawn/island_anchor"
    },{
        "predicate":{
            "custom_model_data":1000347
        },"model":"custom/general/icons/util/minus"
    },{
        "predicate":{
            "custom_model_data":1000348
        },"model":"custom/general/icons/util/plus"
    },{
        "predicate":{
            "custom_model_data":1000349
        },"model":"custom/general/icons/util/question_mark"
    },{
        "predicate":{
            "custom_model_data":1000350
        },"model":"custom/general/items/design_templates/amber_scroll"
    },{
        "predicate":{
            "custom_model_data":1000351
        },"model":"custom/general/items/design_templates/amethyst_scroll"
    },{
        "predicate":{
            "custom_model_data":1000352
        },"model":"custom/general/items/design_templates/bone_scroll"
    },{
        "predicate":{
            "custom_model_data":1000353
        },"model":"custom/general/items/design_templates/cactus_scroll"
    },{
        "predicate":{
            "custom_model_data":1000354
        },"model":"custom/general/items/design_templates/crimson_scroll"
    },{
        "predicate":{
            "custom_model_data":1000355
        },"model":"custom/general/items/design_templates/fire_scroll"
    },{
        "predicate":{
            "custom_model_data":1000356
        },"model":"custom/general/items/design_templates/jade_scroll"
    },{
        "predicate":{
            "custom_model_data":1000357
        },"model":"custom/general/items/design_templates/nautilus_scroll"
    },{
        "predicate":{
            "custom_model_data":1000358
        },"model":"custom/general/items/design_templates/rainbow_scroll"
    },{
        "predicate":{
            "custom_model_data":1000359
        },"model":"custom/general/items/design_templates/ruby_scroll"
    },{
        "predicate":{
            "custom_model_data":1000360
        },"model":"custom/general/items/design_templates/sculk_scroll"
    },{
        "predicate":{
            "custom_model_data":1000361
        },"model":"custom/general/items/treasure_chests/chests/furniture_chest"
    },{
        "predicate":{
            "custom_model_data":1000362
        },"model":"custom/general/items/treasure_chests/chests/golden_chest"
    },{
        "predicate":{
            "custom_model_data":1000363
        },"model":"custom/general/items/treasure_chests/chests/hat_chest"
    },{
        "predicate":{
            "custom_model_data":1000364
        },"model":"custom/general/items/treasure_chests/chests/skin_chest"
    },{
        "predicate":{
            "custom_model_data":1000365
        },"model":"custom/general/items/treasure_chests/chests/wooden_chest"
    },{
        "predicate":{
            "custom_model_data":1000366
        },"model":"custom/general/icons/util/ruby"
    },{
        "predicate":{
            "custom_model_data":1000367
        },"model":"custom/general/items/treasure_chests/keys/default_key"
    },{
        "predicate":{
            "custom_model_data":1000368
        },"model":"custom/factions/items/moonstone"
    },{
        "predicate":{
            "custom_model_data":1000369
        },"model":"custom/factions/items/default_lever"
    },{
        "predicate":{
            "custom_model_data":1000370
        },"model":"custom/factions/items/epic_lever"
    },{
        "predicate":{
            "custom_model_data":1000371
        },"model":"custom/factions/items/legendary_lever"
    },{
        "predicate":{
            "custom_model_data":1000372
        },"model":"custom/general/items/single_ruby"
    },{
        "predicate":{
            "custom_model_data":1000373
        },"model":"custom/general/fishing/xmas_rod/2022/xmas_fishing_rod_2022_present"
    },{
        "predicate":{
            "custom_model_data":1000374
        },"model":"custom/general/fishing/xmas_rod/2023/xmas_fishing_rod_2023_present"
    },{
        "predicate":{
            "custom_model_data":1000375
        },"model":"custom/general/items/treasure_chests/keys/christmas_key"
    },{
        "predicate":{
            "custom_model_data":1000376
        },"model":"custom/general/items/treasure_chests/chests/christmas_chest"
    },{
        "predicate":{
            "custom_model_data":1000381
        },"model":"custom/general/icons/settings/color_gray_off"
    },{
        "predicate":{
            "custom_model_data":1000382
        },"model":"custom/general/icons/settings/color_gray_on"
    },{
        "predicate":{
            "custom_model_data":1000383
        },"model":"custom/general/icons/settings/color_green_off"
    },{
        "predicate":{
            "custom_model_data":1000384
        },"model":"custom/general/icons/settings/color_green_on"
    },{
        "predicate":{
            "custom_model_data":1000385
        },"model":"custom/general/icons/settings/color_lime_off"
    },{
        "predicate":{
            "custom_model_data":1000386
        },"model":"custom/general/icons/settings/color_lime_on"
    },{
        "predicate":{
            "custom_model_data":1000387
        },"model":"custom/general/icons/settings/color_purple_off"
    },{
        "predicate":{
            "custom_model_data":1000388
        },"model":"custom/general/icons/settings/color_purple_on"
    },{
        "predicate":{
            "custom_model_data":1000389
        },"model":"custom/general/icons/settings/color_red_off"
    },{
        "predicate":{
            "custom_model_data":1000390
        },"model":"custom/general/icons/settings/color_red_on"
    },{
        "predicate":{
            "custom_model_data":1000391
        },"model":"custom/general/icons/settings/color_yellow_off"
    },{
        "predicate":{
            "custom_model_data":1000392
        },"model":"custom/general/icons/settings/color_yellow_on"
    },{
        "predicate":{
            "custom_model_data":1000393
        },"model":"custom/general/icons/settings/settings"
    },{
        "predicate":{
            "custom_model_data":1000394
        },"model":"custom/general/icons/settings/switch_off"
    },{
        "predicate":{
            "custom_model_data":1000395
        },"model":"custom/general/icons/settings/switch_on"
    },{
        "predicate":{
            "custom_model_data":1000396
        },"model":"custom/general/fishing/pearl"
    },{
        "predicate":{
            "custom_model_data":1000397
        },"model":"custom/general/icons/hotbar/teleport"
    },{
        "predicate":{
            "custom_model_data":1000398
        },"model":"custom/general/icons/hotbar/cosmetics"
    },{
        "predicate":{
            "custom_model_data":1000399
        },"model":"custom/general/icons/hotbar/profile"
    },{
        "predicate":{
            "custom_model_data":1000400
        },"model":"custom/general/icons/hotbar/seasonpass"
    },{
        "predicate":{
            "custom_model_data":1000401
        },"model":"custom/general/icons/hotbar/social"
    },{
        "predicate":{
            "custom_model_data":1000402
        },"model":"custom/general/icons/gamemodes/creative"
    },{
        "predicate":{
            "custom_model_data":1000403
        },"model":"custom/general/icons/teleporter/cosmetic_store"
    },{
        "predicate":{
            "custom_model_data":1000404
        },"model":"custom/general/icons/teleporter/mystery_cave"
    },{
        "predicate":{
            "custom_model_data":1000405
        },"model":"custom/general/icons/teleporter/ruby_mine"
    },{
        "predicate":{
            "custom_model_data":1000406
        },"model":"custom/general/icons/teleporter/spawn"
    },{
        "predicate":{
            "custom_model_data":1000407
        },"model":"custom/lobby/util/red_ruby_minecart_empty"
    },{
        "predicate":{
            "custom_model_data":1000408
        },"model":"custom/general/items/tom_block_coupon"
    },{
        "predicate":{
            "custom_model_data":1000409
        },"model":"custom/general/items/treasure_chests/keys/birthday_key"
    },{
        "predicate":{
            "custom_model_data":1000410
        },"model":"custom/general/items/treasure_chests/keys/easter_key"
    },{
        "predicate":{
            "custom_model_data":1000411
        },"model":"custom/general/items/treasure_chests/keys/halloween_key"
    },{
        "predicate":{
            "custom_model_data":1000412
        },"model":"custom/general/items/treasure_chests/keys/summer_key"
    },{
        "predicate":{
            "custom_model_data":1000413
        },"model":"custom/general/items/treasure_chests/keys/valentine_key"
    },{
        "predicate":{
            "custom_model_data":1000414
        },"model":"custom/general/items/treasure_chests/chests/valentine_chest"
    },{
        "predicate":{
            "custom_model_data":1000415
        },"model":"custom/general/icons/settings/vip"
    },{
        "predicate":{
            "custom_model_data":1000416
        },"model":"custom/general/icons/settings/visibility"
    },{
        "predicate":{
            "custom_model_data":1000417
        },"model":"custom/general/icons/settings/player_jump"
    },{
        "predicate":{
            "custom_model_data":1000418
        },"model":"custom/general/icons/settings/party"
    },{
        "predicate":{
            "custom_model_data":1000419
        },"model":"custom/general/icons/settings/mail"
    },{
        "predicate":{
            "custom_model_data":1000420
        },"model":"custom/general/icons/settings/incognito"
    },{
        "predicate":{
            "custom_model_data":1000421
        },"model":"custom/general/icons/settings/friends"
    },{
        "predicate":{
            "custom_model_data":1000422
        },"model":"custom/general/icons/settings/elytra"
    },{
        "predicate":{
            "custom_model_data":1000423
        },"model":"custom/general/icons/settings/chat"
    },{
        "predicate":{
            "custom_model_data":1000424
        },"model":"custom/general/fishing/baits/bloody_bait"
    },{
        "predicate":{
            "custom_model_data":1000425
        },"model":"custom/general/fishing/baits/jelly_bait"
    },{
        "predicate":{
            "custom_model_data":1000426
        },"model":"custom/general/error/pretty_error"
    },{
        "predicate":{
            "custom_model_data":1000428
        },"model":"custom/kakiklicker/items/cactus_factory_icon"
    },{
        "predicate":{
            "custom_model_data":1000429
        },"model":"custom/kakiklicker/items/cactus_storage_icon"
    },{
        "predicate":{
            "custom_model_data":1000430
        },"model":"custom/kakiklicker/items/coal_mine_icon"
    },{
        "predicate":{
            "custom_model_data":1000431
        },"model":"custom/kakiklicker/items/coal_storage_icon"
    },{
        "predicate":{
            "custom_model_data":1000432
        },"model":"custom/kakiklicker/items/pipe_icon"
    },{
        "predicate":{
            "custom_model_data":1000433
        },"model":"custom/general/items/treasure_chests/chests/easter_chest"
    },{
        "predicate":{
            "custom_model_data":1000434
        },"model":"custom/general/icons/mystery_eggs/cosmetic_egg"
    },{
        "predicate":{
            "custom_model_data":1000435
        },"model":"custom/general/icons/mystery_eggs/crystal_egg"
    },{
        "predicate":{
            "custom_model_data":1000436
        },"model":"custom/general/icons/mystery_eggs/seasonpass_egg"
    },{
        "predicate":{
            "custom_model_data":1000437
        },"model":"custom/lobby/util/crystal_big"
    },{
        "predicate":{
            "custom_model_data":1000438
        },"model":"custom/general/icons/crystal_display"
    },{
        "predicate":{
            "custom_model_data":1000439
        },"model":"custom/general/icons/ruby_display"
    },{
        "predicate":{
            "custom_model_data":1000440
        },"model":"custom/general/icons/discord_display"
    },{
        "predicate":{
            "custom_model_data":1000441
        },"model":"custom/minecraft_party/icons/minigames/remember_the_path"
    },{
        "predicate":{
            "custom_model_data":1000442
        },"model":"custom/minecraft_party/util/laser_beam"
    },{
        "predicate":{
            "custom_model_data":1000443
        },"model":"custom/kakiklicker/booster/coal_booster"
    },{
        "predicate":{
            "custom_model_data":1000444
        },"model":"custom/kakiklicker/booster/factory_booster"
    },{
        "predicate":{
            "custom_model_data":1000445
        },"model":"custom/kakiklicker/booster/farm_booster"
    },{
        "predicate":{
            "custom_model_data":1000446
        },"model":"custom/kakiklicker/booster/hoe_booster"
    },{
        "predicate":{
            "custom_model_data":1000447
        },"model":"custom/kakiklicker/booster/mob_booster"
    },{
        "predicate":{
            "custom_model_data":1000448
        },"model":"custom/kakiklicker/booster/pickaxe_booster"
    },{
        "predicate":{
            "custom_model_data":1000449
        },"model":"custom/general/icons/gamemodes/skyblock_disabled"
    },{
        "predicate":{
            "custom_model_data":1000450
        },"model":"custom/general/icons/settings/sound"
    },{
        "predicate":{
            "custom_model_data":1000451
        },"model":"custom/kakiklicker/items/potted_cactus"
    },{
        "predicate":{
            "custom_model_data":1000452
        },"model":"custom/kakiklicker/items/spring"
    },{
        "predicate":{
            "custom_model_data":1000453
        },"model":"custom/kakiklicker/items/valve"
    },{
        "predicate":{
            "custom_model_data":1000454
        },"model":"custom/kakiklicker/items/wood_leftover"
    },{
        "predicate":{
            "custom_model_data":1000455
        },"model":"custom/kakiklicker/items/metal_scrap"
    },{
        "predicate":{
            "custom_model_data":1000456
        },"model":"custom/kakiklicker/items/lever"
    },{
        "predicate":{
            "custom_model_data":1000457
        },"model":"custom/kakiklicker/items/gear"
    },{
        "predicate":{
            "custom_model_data":1000458
        },"model":"custom/kakiklicker/items/engine"
    },{
        "predicate":{
            "custom_model_data":1000459
        },"model":"custom/kakiklicker/items/drill"
    },{
        "predicate":{
            "custom_model_data":1000460
        },"model":"custom/kakiklicker/items/conveyor_belt"
    },{
        "predicate":{
            "custom_model_data":1000461
        },"model":"custom/kakiklicker/items/cables"
    },{
        "predicate":{
            "custom_model_data":1000462
        },"model":"custom/kakiklicker/items/bolt"
    },{
        "predicate":{
            "custom_model_data":1000463
        },"model":"custom/kakiklicker/items/circuit_board"
    },{
        "predicate":{
            "custom_model_data":1000464
        },"model":"custom/kakiklicker/items/piston"
    },{
        "predicate":{
            "custom_model_data":1000465
        },"model":"custom/general/items/treasure_chests/chests/summer_chest"
    },{
        "predicate":{
            "custom_model_data":1000466
        },"model":"custom/general/items/treasure_chests/chests/birthday_chest"
    },{
        "predicate":{
            "custom_model_data":1000467
        },"model":"custom/general/items/treasure_chests/chests/halloween_chest"
    },{
        "predicate":{
            "custom_model_data":1000468
        },"model":"custom/general/specialitems/image_map"
    },{
        "predicate":{
            "custom_model_data":1000469
        },"model":"custom/general/items/lottery_ticket"
    },{
        "predicate":{
            "custom_model_data":1000470
        },"model":"custom/kakiklicker/pipes/valve_handle_plug"
    },{
        "predicate":{
            "custom_model_data":1000471
        },"model":"custom/general/items/package"
    },{
        "predicate":{
            "custom_model_data":1000472
        },"model":"custom/general/items/gift_shake"
    },{
        "predicate":{
            "custom_model_data":1000473
        },"model":"custom/general/items/gift"
    },{
        "predicate":{
            "custom_model_data":1000474
        },"model":"custom/general/items/package_shake"
    },{
        "predicate":{
            "custom_model_data":1000475
        },"model":"custom/general/armor_items/christmas_armor/christmas_boots"
    },{
        "predicate":{
            "custom_model_data":1000476
        },"model":"custom/general/armor_items/christmas_armor/christmas_chestplate"
    },{
        "predicate":{
            "custom_model_data":1000477
        },"model":"custom/general/armor_items/christmas_armor/christmas_helmet"
    },{
        "predicate":{
            "custom_model_data":1000478
        },"model":"custom/general/armor_items/christmas_armor/christmas_leggings"
    },{
        "predicate":{
            "custom_model_data":1000479
        },"model":"custom/general/items/design_templates/christmas_scroll"
    },{
        "predicate":{
            "custom_model_data":1000480
        },"model":"custom/general/items/private_teleport_default"
    },{
        "predicate":{
            "custom_model_data":1000481
        },"model":"custom/minecraft_party/icons/minigames/tnt_spleef"
    },{
        "predicate":{
            "custom_model_data":1000482
        },"model":"custom/minecraft_party/icons/minigames/tumble_tactics"
    },{
        "predicate":{
            "custom_model_data":1000483
        },"model":"custom/kakiklicker/items/uranium_mine_icon"
    },{
        "predicate":{
            "custom_model_data":1000484
        },"model":"custom/kakiklicker/items/uranium_storage_icon"
    },{
        "predicate":{
            "custom_model_data":1000485
        },"model":"custom/kakiklicker/items/power_plant_icon"
    },{
        "predicate":{
            "custom_model_data":1000486
        },"model":"custom/kakiklicker/items/cooling_machine_icon"
    },{
        "predicate":{
            "custom_model_data":1000487
        },"model":"custom/kakiklicker/items/collector_machine_icon"
    },{
        "predicate":{
            "custom_model_data":1000488
        },"model":"custom/kakiklicker/items/coal_blast_furnace_icon"
    },{
        "predicate":{
            "custom_model_data":1000489
        },"model":"custom/kakiklicker/items/mobility_skill"
    },{
        "predicate":{
            "custom_model_data":1000490
        },"model":"custom/kakiklicker/items/looting_skill"
    },{
        "predicate":{
            "custom_model_data":1000491
        },"model":"custom/kakiklicker/items/defense_skill"
    },{
        "predicate":{
            "custom_model_data":1000492
        },"model":"custom/kakiklicker/items/attack_skill"
    },{
        "predicate":{
            "custom_model_data":1000493
        },"model":"custom/kakiklicker/items/uranium_ore"
    },{
        "predicate":{
            "custom_model_data":1000494
        },"model":"custom/general/icons/settings/chat_local"
    },{
        "predicate":{
            "custom_model_data":1000495
        },"model":"custom/general/icons/settings/chat_trade"
    },{
        "predicate":{
            "custom_model_data":1000496
        },"model":"custom/general/icons/settings/chat_en"
    },{
        "predicate":{
            "custom_model_data":1000497
        },"model":"custom/general/icons/settings/chat_build"
    },{
        "predicate":{
            "custom_model_data":1000498
        },"model":"custom/general/icons/settings/chat_global"
    },{
        "predicate":{
            "custom_model_data":1000499
        },"model":"custom/general/icons/settings/chat_de"
    },{
        "predicate":{
            "custom_model_data":1000500
        },"model":"custom/kakiklicker/items/uranium_rod"
    },{
        "predicate":{
            "custom_model_data":1000501
        },"model":"custom/kakiklicker/items/uranium_barrel"
    },{
        "predicate":{
            "custom_model_data":1000502
        },"model":"custom/kakiklicker/items/fan"
    },{
        "predicate":{
            "custom_model_data":1000503
        },"model":"custom/kakiklicker/items/cooling_parts"
    },{
        "predicate":{
            "custom_model_data":1000504
        },"model":"custom/kakiklicker/booster/coal_furnace_booster"
    },{
        "predicate":{
            "custom_model_data":1000505
        },"model":"custom/kakiklicker/booster/cooling_booster"
    },{
        "predicate":{
            "custom_model_data":1000506
        },"model":"custom/kakiklicker/booster/powerplant_booster"
    },{
        "predicate":{
            "custom_model_data":1000507
        },"model":"custom/kakiklicker/booster/uranium_mine_booster"
    },{
        "predicate":{
            "custom_model_data":1000508
        },"model":"custom/general/items/design_templates/sweetheart_scroll"
    },{
        "predicate":{
            "custom_model_data":1000509
        },"model":"custom/general/icons/gamemodes/only_up"
    },{
        "predicate":{
            "custom_model_data":1000510
        },"model":"custom/general/icons/minigames/coop_invite"
    },{
        "predicate":{
            "custom_model_data":1000511
        },"model":"custom/general/icons/minigames/world_switch"
    },{
        "predicate":{
            "custom_model_data":1000512
        },"model":"custom/general/icons/teleporter/nether_portal"
    },{
        "predicate":{
            "custom_model_data":1000513
        },"model":"custom/general/icons/settings/chat_vip"
    }]}

    {
        "providers":[{
        "type":"space", "advances":{
            "":-8, "":-80, "":-116, "":-7, "":-18, "":-7, "":7, "":18, "":-1, "":-2, "":-4, "":-8, "":
            -16, "":-32, "":-64, "":-128, "":-256, "":-512, "":1, "":2, "":4, "":8, "":16, "":32, "":64, "":
            128, "":256, "":512
        }
    },{
        "type":"bitmap", "file":"minecraft:customfont/inventories/misc/back.png", "ascent":9, "height":16, "chars":[
        ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/misc/new-back.png", "ascent":13, "height":14, "chars":[
        ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/tabs/tabs_item_categories.png", "ascent":-2, "height":
        20, "chars":["", "", "", "", "", "", "", "", ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/overlays/ui_1row.png", "ascent":13, "height":
        35, "chars":[""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/overlays/ui_2row.png", "ascent":13, "height":
        54, "chars":[""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/overlays/ui_3row.png", "ascent":13, "height":
        72, "chars":["", ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/overlays/ui_4row.png", "ascent":13, "height":
        90, "chars":["", "", ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/overlays/ui_5row.png", "ascent":13, "height":
        108, "chars":["", ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/overlays/ui_6row.png", "ascent":13, "height":
        126, "chars":["", "", ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/overlays/ui_anvil.png", "ascent":13, "height":
        83, "chars":[""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/misc/bar_seasonpass.png", "ascent":-44, "height":
        6, "chars":["", "", "", "", "", "", "", ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/misc/bar_realms.png", "ascent":-46, "height":
        6, "chars":["", "", "", "", "", "", "", "", ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/tabs/ui_navigations_2.png", "ascent":-6, "height":
        14, "chars":["", "", "", "", "", "", "", "", "", ""]},{
        "type":"bitmap", "file":"minecraft:customfont/inventories/tabs/ui_navigations_3.png", "ascent":-6, "height":
        14, "chars":["", "", "", "", "", "", "", "", ""]}]}

     */
}
